version: "2"

services:
    certbot-ssl:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: certbot-ssl
        privileged: true
        ports:
            - 8080:8080
        environment:
            - DOMAIN=foo.bar
            - WEB_PORT=8080
            # - DRY_RUN=1
        volumes:
            - ./creds:/root/creds
        